name: Android CI Releases

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build  # Ensure we build the release variant

    - name: Check APK file existence
      run: |
        echo "Listing APK files in the build folder:"
        ls ./app/build/outputs/apk/  # List release APK files to debug

    - name: Compress build folder
      run: |
        ZIP_FILE="android-build-$(date +'%Y%m%d%H%M%S').zip"
        echo "Compressing android/app/build directory into $ZIP_FILE"
        zip -r $ZIP_FILE ./app/build  # Compress the build directory
        ls -lh $ZIP_FILE  # List the compressed file
        echo "ZIP_FILE=$ZIP_FILE" >> $GITHUB_ENV  # Set ZIP_FILE as an environment variable for later use

    - name: Create GitHub Release
      id: create_release
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"  # Create a unique version tag
        echo "Creating release with tag: $TAG_NAME"
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV  # Set TAG_NAME as an environment variable for later use

    - name: Upload Release to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}  # Use the tag created earlier
        files: ${{ env.ZIP_FILE }}  # Upload the compressed .zip file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure GH_TOKEN is set
