name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Create Release
      id: create_release
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"  # Create a unique version tag
        echo "Creating release with tag: $TAG_NAME"
        gh release create $TAG_NAME ./app/build/outputs/apk/release/app-release.apk --title "Release $TAG_NAME" --notes "Automated release"

    - name: Upload APK to Release
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
        gh release upload $TAG_NAME ./app/build/outputs/apk/release/app-release.apk --clobber
